name = "callback4apptypescript"
main = "src/index.ts"
compatibility_date = "2026-07-28"

[triggers]
crons = ["0 0,6,12,18 * * *", "12 1,7,13,19 * * *", "24  2,8,14,20 * * *", "36 3,9,15,21 * * *", "48 4,10,16,22 * * *"]
